### ISSUE TITLE
Symbol hover+refs work, but can't jump to def

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/python-langserver#11]
Several symbols in this file have this issue: I can hover to see a description/comments and type info, I can get local refs, but I can't jump to def. This symbol is an example.

https://sourcegraph.com/github.com/django/django/-/blob/django/urls/utils.py#L41:26

**Comment by keegancsmith** [comment]
Thanks. This is just a bug in the def code. Will fix and close once shipped.

**Comment by keegancsmith** [comment]
I've made it so it doesn't throw an exception in the backend. However, `AttributeError` is part of the python stdlib, and we do not currently support interacting with it (but will!)

**Comment by keegancsmith** [comment]
![image](https://cloud.githubusercontent.com/assets/187831/25797567/140a72ce-33de-11e7-9505-3162293dfb52.png)

much better :)
