### ISSUE TITLE
Crashing often in production with exit code 139

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/python-langserver#15]
This is happening very often now thanks to increased traffic from the browser extension. Unfortunately the logs are very bare, so I'm not sure why this is happening. Exit code 139 means segfault, which makes this more perplexing to debug. I'll see if I can enable coredumps. cc @akhleung

**Comment by akhleung** [comment]
After deploying the latest version (ddd5444a957d8ecc2f1ca188c4acef9bae98995a), the crashes seem to have stopped. Will keep an eye on it and close this ticket if a day or two pass without (m)any crashes.

**Comment by akhleung** [comment]
Ran for a day without crashing; I'm assuming that it was inadvertently fixed by the numerous recent changes. Closing for now; will reopen if the issue resurfaces.
