### ISSUE TITLE
Broken stdio mode in Python Langserver

### ISSUE THREAD

**Issue by vparfonov** [sourcegraph/python-langserver#17]
Try to strart LS like `python3.5 python-langserver.py --mode stdio` and got error 
```
INFO:root:Reading on stdin, writing on stdout
Traceback (most recent call last):
  File "python-langserver.py", line 11, in <module>
    main()
  File "/home/user/che/ls-python/langserver/langserver.py", line 473, in main
    s.run()
  File "/home/user/che/ls-python/langserver/langserver.py", line 38, in run
    request = self.conn.read_message()
AttributeError: 'ReadWriter' object has no attribute 'read_message'
```

**Comment by keegancsmith** [comment]
@vparfonov thanks for trying out the language server. Note we are actively developing this with the server on sourcegraph.com use case in mind, so you may notice regressions for vscode (which uses stdio). I'd suggest in the mean time trying out https://github.com/palantir/python-language-server/ for vscode use. However, we will target the desktop use case once we have stabilised it for our production.

I'll add a note to the README.md with the advice for using palantir's LS server.

**Comment by vparfonov** [comment]
@keegancsmith thanks for answer
