### ISSUE TITLE
Fails using stdio mode

### ISSUE THREAD

**Issue by Phantomape** [sourcegraph/python-langserver#30]
I tried to use stdio mode, but I found out that variable conn does not have a read_message() method. Will you fix this bug?
`ERROR:langserver.langserver:Unexpected error: 'ReadWriter' object has no attribute 'read_message'
Traceback (most recent call last):
  File "/home/phantomape/Projects/python-langserver/langserver/langserver.py", line 45, in run
    request = self.conn.read_message()
AttributeError: 'ReadWriter' object has no attribute 'read_message'`

**Comment by keegancsmith** [comment]
cc @akhleung @beyang

**Comment by akhleung** [comment]
Thanks for trying our language server! It's still under active development and currently targeted towards our cloud service, so we haven't put much development effort into the local/desktop use case. We do plan on making it work with VS Code eventually, but in the meantime you can try https://github.com/palantir/python-language-server/

**Comment by Phantomape** [comment]
Thanks, the one from palantir suits my needs
