### ISSUE TITLE
Jedi thread safety

### ISSUE THREAD

**Issue by renfredxh** [sourcegraph/python-langserver#4]
Jedi [docs state](https://jedi.readthedocs.io/en/latest/docs/development.html#module-jedi.cache) the API is not thread safe. This could pose as an issue to our language server, which spawns a new thread for each TCP connection.

The thread safety issues seem to be related to cache variables within the library. We may be able to modify this behavior to use a thread safe cache mechanism instead.

**Comment by keegancsmith** [comment]
We just switched to a forking model to fix this issue.
