### ISSUE TITLE
python 2 support?

### ISSUE THREAD

**Issue by ags799** [sourcegraph/python-langserver#5]
Hi, seems that this language server is Python 3 specific (please correct me if I'm wrong)? If so, what do you think about adding Python 2 support? I'd be happy to help.

**Comment by renfredxh** [comment]
The current plan is support python versions 2 and 3. The langserver is still under active development so not all features between both versions may be complete yet. 

Thanks for your offer to help, once everything is in a more stable state we'll update the issue tracker and you can jump in on anything that interests you there.

**Comment by ags799** [comment]
That's fine, totally understandable. Just curious, do you mind if I fork the repo and work on features myself? I ask because I can't seem to find a license. Thanks.

**Comment by renfredxh** [comment]
Thanks for pointing that out, the project license has been updated.
