### ISSUE TITLE
git history should have more info

### ISSUE THREAD

**Issue by shawnma** [sourcegraph/python-langserver#61]
Currently when you look at the history of a file, it has only git change id and summary. It would be better if we can have author and date information. It would be even better if we can have diff support for two versions.

**Comment by keegancsmith** [comment]
Hey @shawnma, did you mean to file this issue in this repo? It seems to be about git history, while this repository is concerned with python code analysis.

**Comment by shawnma** [comment]
Yeah NM. the 'report issue' linked me here. Will report it elsewhere.

**Comment by shawnma** [comment]
So many repos..any recommendation on which repo to file this enhancement request?

**Comment by keegancsmith** [comment]
Sorry. I suppose you want to file in our main repo `sourcegraph`
