### ISSUE TITLE
Python Langserver don't work with Eclipse Che

### ISSUE THREAD

**Issue by vparfonov** [sourcegraph/python-langserver#7]
Che team want to try your Python LS, we have added it to package but language service didn't respond.
Can you please try this PR https://github.com/eclipse/che/pull/3207

**Comment by beyang** [comment]
Hey @vparfonov, thanks for filing. I'm looking through the console output at https://ci.codenvycorp.com/job/che-pullrequests-build/1169/console, but I'm having trouble deciphering the error. I search for "Python" but all I see are success messages. Are there any corresponding logs from the Python language server?

**Comment by vparfonov** [comment]
We not reproduce problem after updating to your current version in master ([this commit working well for us](https://github.com/sourcegraph/python-langserver/commit/6a72b3ae1fb927881cb5bebce818a3e821d3f77e)) so we close issue. 

PR in Eclipse Che https://github.com/eclipse/che/pull/3693
